using System.Text.Json;
using AccessWatch.Core;
using AccessWatch.Notifications;

namespace AccessWatch.Service;

/// <summary>
/// Creates demo AccessWatch observations so the dashboard can be exercised without waiting for real network changes.
/// </summary>
public sealed class AccessWatchEventSimulator
{
    private readonly IAccessWatchRepository repository;
    private readonly NotificationMessageFactory notificationFactory;
    private readonly ITrayNotificationService trayNotificationService;

    /// <summary>
    /// Initializes a new simulator that persists and notifies through the normal AccessWatch paths.
    /// </summary>
    /// <param name="repository">Repository used to save simulated observations.</param>
    /// <param name="notificationFactory">Factory used to build the user-facing notification.</param>
    /// <param name="trayNotificationService">Tray notification sink.</param>
    public AccessWatchEventSimulator(
        IAccessWatchRepository repository,
        NotificationMessageFactory notificationFactory,
        ITrayNotificationService trayNotificationService)
    {
        this.repository = repository;
        this.notificationFactory = notificationFactory;
        this.trayNotificationService = trayNotificationService;
    }

    /// <summary>
    /// Creates one simulated device, application, listening port, event, and notification.
    /// </summary>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The number of events created.</returns>
    public async Task<int> TriggerDemoEventAsync(CancellationToken cancellationToken)
    {
        await repository.InitializeAsync(cancellationToken);

        var now = DateTimeOffset.UtcNow;
        var deviceId = await repository.UpsertDeviceAsync(CreateDevice(now), cancellationToken);
        var applicationId = await repository.UpsertApplicationAsync(CreateApplication(now), cancellationToken);
        var port = CreatePort(now, applicationId);
        await repository.UpsertPortAsync(port, applicationId, cancellationToken);

        var assessment = new PortRiskAssessment(
            RiskLevel.High,
            RiskStatus.HighRisk,
            NotificationAction.AskBeforeAllow,
            "Simulated Remote Admin opened a network-reachable port.",
            "This simulated service is reachable from other devices, just like a real exposed listener would be.",
            "Use this event to verify dashboard review, toast, and inventory workflows.");
        var notification = notificationFactory.Create(assessment);

        await repository.AddNetworkEventAsync(
            new NetworkEvent
            {
                EventType = "NewListeningPort",
                SourceIp = "192.168.1.240",
                SourceDeviceId = deviceId,
                DestinationIp = port.LocalAddress,
                DestinationPort = port.PortNumber,
                Protocol = port.Protocol,
                Direction = "Inbound",
                ApplicationId = applicationId,
                RiskLevel = assessment.RiskLevel,
                Summary = assessment.Summary,
                DetailsJson = BuildDetailsJson(assessment),
                WasUserNotified = true,
                CreatedUtc = now
            },
            cancellationToken);
        await trayNotificationService.ShowAsync(notification, cancellationToken);

        return 1;
    }

    private static NetworkDevice CreateDevice(DateTimeOffset now)
    {
        return new NetworkDevice
        {
            IpAddress = "192.168.1.240",
            MacAddress = "02:AC:CE:55:10:01",
            Hostname = "simulated-nas",
            Vendor = "AccessWatch Lab",
            DeviceTypeGuess = "Network storage",
            FirstSeenUtc = now,
            LastSeenUtc = now,
            LastConfirmedUtc = now,
            TrustStatus = TrustStatus.Unknown,
            RiskStatus = RiskStatus.Suspicious,
            Notes = "Simulated device generated by AccessWatch."
        };
    }

    private static ApplicationIdentity CreateApplication(DateTimeOffset now)
    {
        return new ApplicationIdentity
        {
            DisplayName = "Simulated Remote Admin",
            ProcessName = "sim-remote-admin",
            FilePath = @"C:\AccessWatch\SimulatedRemoteAdmin.exe",
            Publisher = "Unknown publisher",
            ProductName = "AccessWatch Simulator",
            FileDescription = "Simulated remote administration service",
            SignatureStatus = SignatureStatus.Unsigned,
            InstallFolder = @"C:\AccessWatch",
            ParentProcessName = "accesswatch",
            FirstSeenUtc = now,
            LastSeenUtc = now,
            TrustStatus = TrustStatus.Unknown,
            Notes = "Simulated application generated by AccessWatch."
        };
    }

    private static ListeningPort CreatePort(DateTimeOffset now, long applicationId)
    {
        return new ListeningPort
        {
            PortNumber = 9443,
            Protocol = "TCP",
            LocalAddress = "0.0.0.0",
            Reachability = PortReachability.NetworkReachable,
            OwningProcessId = 9443,
            Application = CreateApplication(now) with { ApplicationId = applicationId },
            FirstSeenUtc = now,
            LastSeenUtc = now,
            TrustStatus = TrustStatus.Unknown,
            RiskStatus = RiskStatus.HighRisk
        };
    }

    private static string BuildDetailsJson(PortRiskAssessment assessment)
    {
        var details = new
        {
            simulated = true,
            whatHappened = "A simulated listening TCP port appeared.",
            app = "Simulated Remote Admin",
            processName = "sim-remote-admin",
            reachability = PortReachability.NetworkReachable.ToString(),
            whyItMatters = assessment.WhyItMatters,
            suggestedAction = assessment.SuggestedAction
        };

        return JsonSerializer.Serialize(details);
    }
}

